### ISSUE TITLE
Filters and defaults.

### ISSUE THREAD

**Issue by jdickey** [DamirSvrtan/fasterer#1]
This *probably* shouldn't look at what's in `vendor`, and arguably `config` by default, yet I see no [configuration option](https://github.com/DamirSvrtan/fasterer#configuration) for limiting matches. Is that on the radar, or am I missing something?

**Comment by DamirSvrtan** [comment]
Yep, that is on the top of the list. Will close this task once i release it. I know a couple of gems that do path ignoring, do you have a preference or an example of something really good?

**Comment by DamirSvrtan** [comment]
Hey @jdickey I've added an option to ignore file paths, please check the README. However I haven't added any of the path to defaults.

**Comment by DamirSvrtan** [comment]
I will try to add a global configuration you could put in your HOME folder or something similar like Rubocop does.

**Comment by jdickey** [comment]
@DamirSvrtan Looks good; pretty much what I expected YAML config to look like. Gives me a much more usable report. Thanks!
