### ISSUE TITLE
Request - Detect Enumerable#select + last

### ISSUE THREAD

**Issue by almostwhitehat** [DamirSvrtan/fasterer#2]
Detect Enumerable#select + last, suggest Array#reverse + detect

**Comment by DamirSvrtan** [comment]
I get Enumerable#select + last, but why would someone do Array#reverse + detect? It's early in the morning and I'm probably missing something :)

**Comment by DamirSvrtan** [comment]
Indeed it was way to early for me :) 

Do you have this benchmarked?

Maybe you could submit this to fast-ruby: https://github.com/JuanitoFatas/fast-ruby

**Comment by DamirSvrtan** [comment]
I've added this to version 0.1.7. Thnx for your contribution!
