### ISSUE TITLE
Parallel assignment vs sequential assignment is providing wrong suggestion

### ISSUE THREAD

**Issue by monfresh** [DamirSvrtan/fasterer#20]
I believe the latest results from fast-ruby show that [Parallel assignment is faster than sequential assignmnent](https://github.com/JuanitoFatas/fast-ruby#parallel-assignment-vs-sequential-assignment-code). I ran benchmarks on my own code as well and sequential assignment is reported as slower. Currently, fasterer is saying that `Parallel assignment is slower than sequential assignment.`, which I believe is wrong.

**Comment by yous** [comment]
At first, the result was the reverse, but this is changed recently by fixing benchmark code. See https://github.com/JuanitoFatas/fast-ruby/pull/50#issue-98586885.

**Comment by DamirSvrtan** [comment]
I've removed this check from fasterer. Stylewise I don't want people to do parallel assignment without thinking it through.
