### ISSUE TITLE
Error message - please consider improving it

### ISSUE THREAD

**Issue by shevegen** [DamirSvrtan/fasterer#24]
Hi,

I was trying to use fasterer on a single .rb file:

fasterer wlan.rb 

I get the following error message:

    Fasterer was unable to process some files because the
    internal parser is not able to read some characters or
    has timed out. Unprocessable files were:

-----------------------------------------------------
wlan.rb

---

This error message does not tell me much. What are the
bad characters? Why can it not process?

For reference, the file wlan.rb is available at:

  https://gist.github.com/shevegen/3fe9e1a35b1b9dd52fee

**Comment by DamirSvrtan** [comment]
Hey, I've just released 0.2.0 - it has an improved error message.

For this file it will throw a parse error because it says it has a unexpected comma:

```ruby
  alias _method :_, :esystem
```

Thank you for reporting this and sorry for the extra late reply.
