### ISSUE TITLE
How to make fasterer work on .rb files only

### ISSUE THREAD

**Issue by manorie** [DamirSvrtan/fasterer#25]
I have a ruby project has a folder structure like,
token\
token\token.rb
token\lib\base.rb
token\lib\parts.rb
...
I could not find a way to work fasterer on my project. It does work in my rails projects until receiving an error like,

"Fasterer was unable to process some files because the
internal parser is not able to read some characters or
has timed out. Unprocessable files were:"

I really liked the idea of this gem and want to use it, but maybe documentation is not enough or there is a problem using it on custom ruby projects. Thanks.

**Comment by DamirSvrtan** [comment]
Hey, it's not tied to any folder structure. Could you send me one file to see why it says they're unprocessable?

**Comment by manorie** [comment]
Hey, I thought it is not working because did not received a message like, inspected 10 files, process quit, no offerings etc. A finished message can be a good improvement for such confusions.
For instance, in carrierwave (master branch) gem it gives a time out error at,
lib/generators/templates/uploader.rb

**Comment by DamirSvrtan** [comment]
Hey, I've added a statistics output:

```shell
Fasterer was unable to process some files because the
internal parser is not able to read some characters or
has timed out. Unprocessable files were:
-----------------------------------------------------
user.rb - RubyParser::SyntaxError - unterminated string meets end of file. near line 1: ""

1 file inspected, 0 offenses detected, 1 unparsable file found
```

Check it out in 0.2.1

As for the uploader file that you've mentioned - I can't do anything about it since it's unparsable - it is a template for Rails but has a .rb extension. I can't detect that it's a template file. If you have any suggestions, I'm up for it.

Also, sorry for the extra late reply and fix.
