### ISSUE TITLE
Don’t advise to use each_key if the receiver doesn’t support it

### ISSUE THREAD

**Issue by bfontaine** [DamirSvrtan/fasterer#33]
`fasterer` advises to use `each_key` instead of `keys.each` even on objects that don’t support `each_key`:

```rb
# keys_each.rb
class KeysProvider
  def keys; []; end
end

kp = KeysProvider.new
kp.keys.each do |k|
  puts k
end
```

```shellSession
$ fasterer keys_each.rb
keys_each.rb
Hash#keys.each is slower than Hash#each_key. Occurred at lines: 6.

```

**Comment by DamirSvrtan** [comment]
Hough, this will be a tough one.

**Comment by radarek** [comment]
It's not tough. It's impossible one. Looking only at the source you can't tell if variable `x` points to object which implements specific method. It's related to dynamic nature of Ruby.

**Comment by bfontaine** [comment]
Can’t you check only the hash variables? You’d miss custom classes that implement both `keys` and `each_key` but that’d still cover 99% of the use-cases.

**Comment by radarek** [comment]
You can't do it too. In theory you could try to track how and when variables are created but in practice it's still an trial & error effort. Suppose you have a method:

```ruby
def foo(x)
  x.keys.each { |key| }
end
```

How can we know if we can replace `x.keys.each` with `x.each_key`? Is `x` an array, a hash or MyCustomClass instace? And what if you call it like this:

```ruby
foo(rand(2) == 0 ? {} : MyCustomClass.new)
```

**Comment by bfontaine** [comment]
You’re right.
