### ISSUE TITLE
Is this tool still maintained?

### ISSUE THREAD

**Issue by mensfeld** [DamirSvrtan/fasterer#44]
Hey there, I can see, that there are some PRs and that the code haven't been updated for quite a while. Just wanted to know, whether or not it is still maintained.

**Comment by DamirSvrtan** [comment]
Hey @mensfeld, the maintenance will continue, sorry, did not have the time in the last couple of months to do so. Will do my best. If you want, I could give you the github permissions to help me if that's something you'd be interested in.

**Comment by mensfeld** [comment]
@DamirSvrtan  thank you. I was just wondering whether or not it is a good idea to add it to my stack, but I know now that it is.

Unfortunately I have a lot o OSS going on myself, so sorry, but won't be able to contribute to a next one :(
