### ISSUE TITLE
Ruby 2.5 support

### ISSUE THREAD

**Issue by mensfeld** [DamirSvrtan/fasterer#46]
```
NOTE: RubyParser::V25 undefined, using RubyParser::V24
```

**Comment by DamirSvrtan** [comment]
Hey @mensfeld, I've pinged the ruby parser gem maintainers to get a new release from them. Unfortunately I can't do anything until we get a new release from them as these warnings are coming from that lib, not from fasterer.

Thanks for reporting!

**Comment by graywolf** [comment]
There's a ruby_parser 3.11 releases on 15th, so this is probably solved? At least I do not see any warnings on 2.5.

**Comment by DamirSvrtan** [comment]
Bumped, if you install fasterer version 0.4.1 these should go away! Ping me if there's any more problems!

**Comment by mensfeld** [comment]
@DamirSvrtan I can confirm that it works:

![zrzut ekranu z 2018-04-04 17 09 38](https://user-images.githubusercontent.com/392754/38316536-3ebf186a-382b-11e8-94c4-387d6af3d5da.png)

Thanks!

**Comment by DamirSvrtan** [comment]
Hi @mensfeld, can you please tell me what libs and CI are you using to show these messages from fasterer?

**Comment by mensfeld** [comment]
Hey @DamirSvrtan, I use something that I've created for myself.

I was tired of having to upgrade all the tools like (awesome) fasterer for all the projects that I work with and having to have them in my gemfile, so I wrapped around a lot of tools, added a lot of my own, hooked it up to Github and added per commit review.

It is built it in a a way, that allows me to upgrade the platforms code with the newest versions of given tools and it will automatically analyze all the projects that are hooked up there. That way I don't have to have any non-production libraries or tools in the codebase.

You can see it work here: https://app.coditsu.io/karafka/repositories/karafka

and here's the full list of tools that I currently support: https://app.coditsu.io/karafka/repositories/karafka/validators

You're more than welcome to use it, since you are partially contributing to it via your work!
