### ISSUE TITLE
Root config file for multiple project support

### ISSUE THREAD

**Issue by hlascelles** [DamirSvrtan/fasterer#48]
We have several ruby projects in one repo. We'd like to have the yml file in the root.

Would you be open to a change to have an upwards traversal to find it?

**Comment by DamirSvrtan** [comment]
Sure thing, go for it, I'm open for a PR for this! I believe this is how Rubocop works.

**Comment by hlascelles** [comment]
Done! https://github.com/DamirSvrtan/fasterer/pull/51
