### ISSUE TITLE
ignore rules via comments in source

### ISSUE THREAD

**Issue by jumanjiman** [DamirSvrtan/fasterer#49]
Currently it is possible to either:
* ignore a rule for all files, or
* ignore a file for all rules

It would be nice to be able to fine-tune the configuration, similar to these:
* https://github.com/adrienverge/yamllint/blob/master/docs/disable_with_comments.rst
* https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md#disabling-cops-within-source-code
* https://github.com/koalaman/shellcheck/wiki/Ignore

**Comment by DamirSvrtan** [comment]
Hey @jumanjiman thank you for opening an issue!

Would you be interested in implementing this? If so, could you please firstly elaborate on what you would do?

**Comment by thepanu** [comment]
I took a stab at it. At the moment it is only implemented for scan_rescue.

Idea is to hold method comments in store and if offenses are found then check if they have been included in the comment preceding the method.

My first ever attempt to submit anything, hopefully it is not completely atrocius :)

**Comment by thepanu** [comment]
No rush. As mentioned I did it only for scan_rescue. If you are happy with that, I can then expand to cover the rest as well. 

Also, added test as well.

And I notice that I should've included issue number in all of my commits for them tho show here.
#53

**Comment by DamirSvrtan** [comment]
The PR #53 was closed some time ago, closing this issue as well.
