### ISSUE TITLE
Use tr instead of gsub when grepping plain strings...unneccesary/wrong

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [DamirSvrtan/fasterer#5]
Most of the hits I get are for plain string substitution...

ex., `my_string.gsub('www.', 'dev.') # => replaces www. with dev.`

Yes, I could move that trivial example into a regular expression just to avoid this suggestion, but what's the point in that?

The use of `tr` is such that each character in the 1st argument is replaced by it's corresponding position in the 2nd argument. It isn't a simple find/replace on the entire string. So this suggestion by fasterer yields far too many false positives.

**Comment by DamirSvrtan** [comment]
Ok, so I figure this check should be performed if the gsubs first argument has only one character. I've released fasterer version 0.1.1 with this update.

Thnx very much for reporting this! Didn't know this one.

Please report if you think this isn't okay.

**Comment by JakeTheSnake3p0** [comment]
It might also make sense to word it such that it is a suggestion, not a rule break. The programmer may be trying something like `my_string.gsub('"', '\"')` (escaping double quote).

**Comment by DamirSvrtan** [comment]
Hey @JakeTheSnake3p0, all the stuff that fasterer reports are just speed suggestions. Do you think this wording is better?

`Using tr when replacing one-character plain strings is faster than using gsub`

**Comment by JakeTheSnake3p0** [comment]
`Using tr is faster than gsub when replacing a single-character string with another single character`. I think you'll need to check that both the `from` and `to` strings are both one character. IMO all other circumstances are more than likely appropriate situations to use `gsub`. This suggestion is a dangerous one for those who don't really understand what `tr` is meant for.

**Comment by DamirSvrtan** [comment]
@JakeTheSnake3p0 thnx a lot for your comments, I've updated the gem accordingly. Please do contribute further, loving it!

**Comment by Oppen** [comment]
tr isn't necessarily faster than gsub for replacing a single character by another single character on a string.
I ran the following code:
`
#!/usr/bin/env ruby

require 'benchmark'

ITS=1000000
STR=':' + 'A' * 4096
PATTERN=':'
SUBS=';'

def with_gsub
  ITS.times do
    STR.gsub(PATTERN, SUBS)
  end
end

def with_sub
  ITS.times do
    STR.sub(PATTERN, SUBS)
  end
end

def with_tr
  ITS.times do
    STR.tr(PATTERN, SUBS)
  end
end

def with_gsub!
  ITS.times do
    STR.gsub!(PATTERN, SUBS)
  end
end

def with_sub!
  ITS.times do
    STR.sub!(PATTERN, SUBS)
  end
end

def with_tr!
  ITS.times do
    STR.tr!(PATTERN, SUBS)
  end
end

Benchmark.bm do |b|
  b.report do
    with_gsub
  end

  b.report do
    with_sub
  end

  b.report do
    with_tr
  end

  b.report do
    with_gsub!
  end

  b.report do
    with_sub!
  end
  b.report do
    with_sub!
  end

  b.report do
    with_tr!
  end

end
`
And the results are:
`
       user     system      total        real
   0.993223   0.044383   1.037606 (  1.037635)
   0.566705   0.000000   0.566705 (  0.566719)
   3.051477   0.000025   3.051502 (  3.051568)
   0.141122   0.000013   0.141135 (  0.141141)
   0.140759   0.000008   0.140767 (  0.140773)
   2.705811   0.000000   2.705811 (  2.705861)
`
There's a simple explanation for why sub wins. It only replaces the first appearance, so it stops after the first character. tr has to iterate over the whole string, which is a pathological case.
I have no idea why gsub beats tr, tho, but it is the case, so we can't suggest with such confidence that "tr is faster than gsub when replacing a single character in a string with another single character".
Even stranger is the fact that replacing in place for gsub yields also the same speed as with sub.

**Comment by Arcovion** [comment]
@oppen You have to `.dup` the string to test the in-place ones, otherwise following the first iteration you're only testing the already-replaced string, so the last few results are void.
```ruby
require 'benchmark/ips'

FIND, REPLACE = ?:, ?;
STRING = FIND + ?A * 4096

Benchmark.ips do |bm|
  bm.report 'sub' do
    STRING.sub FIND, REPLACE
  end
  bm.report 'gsub' do
    STRING.gsub FIND, REPLACE
  end
  bm.report 'tr' do
    STRING.tr FIND, REPLACE
  end
  bm.report '[]=' do
    STRING.dup[FIND] = REPLACE
  end
  bm.compare!
end
```
```
Comparison:
                 []=:   324705.7 i/s
                 sub:   306829.9 i/s - 1.06x  slower
                gsub:   141926.8 i/s - 2.29x  slower
                  tr:    20830.0 i/s - 15.59x  slower
```
Using [this method](https://github.com/JuanitoFatas/fast-ruby#stringgsub-vs-stringsub-vs-string-code) from the the upstream [fast-ruby](https://github.com/JuanitoFatas/fast-ruby) project is slightly faster still.
Pull requests are welcome to help document/clarify this better, advising the use of `[]=`/`.sub` when you know there's only a single match.

**Comment by Arcovion** [comment]
It's strange indeed that `gsub` is faster than `tr` here... I would never have predicted that. 
But I guess this is a pathological case that'll be very unlikely in the real world.

**Comment by Oppen** [comment]
That's possibly the case, but I will write a randomized benchmark tomorrow to make sure and come back.

**Comment by Oppen** [comment]
Also, nice spot  Arcovion. They run after we're done with the others, so previous numbers should remain valid.
I'll fix that tomorrow. I'll also try your code and similar cases I found around.
On the cause of this, I don't think I have the skills to find it.

**Comment by Oppen** [comment]
I ran some more extensive benchmarks.
The code is in here: https://pastebin.com/h8BnUQSd
And the results in my machine are here: https://pastebin.com/Kp8NEea6

For reproducibility's sake, I'm running Xubuntu 18.10 on an Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz with 32GiB of RAM, with stock Ruby 2.5.1p57 (2018-03-29 revision 63029).

An explanation to the results may be the following:
tr has constant time with respect to the match ratio, but a greater baseline.
gsub is correlates to the total number of matches, but has a smaller baseline.
Thus, gsub is up to twice as fast as tr for strings with few appearances of the searched character, while it's substantially slower (around 30x for 50% match rate on my setup) when more matches are present.
Bottomline: it requires domain knowledge to determine which is better, but the rule of thumb should be to use tr.
