### ISSUE TITLE
Ruby 2.6 support

### ISSUE THREAD

**Issue by JaniJegoroff** [DamirSvrtan/fasterer#55]
1. Install Ruby stable version 2.6.0
2. Run `fasterer`
```
NOTE: RubyParser::V26 undefined, using RubyParser::V25.
```

**Comment by DamirSvrtan** [comment]
Hi @JaniJegoroff,

Thanks for reporting this, unfortunately I can't do anything about it currently, we'll have to wait until the ruby_parser repo gets updated. Raising an issue over there.

**Comment by DamirSvrtan** [comment]
The ruby_parser team has released support for Ruby 2.6.0 today so I have released a new version of fasterer that supports 2.6 as well. it's on rubygems, version `0.5.1`. 

Thanks for reporting the issue!
