### ISSUE TITLE
Array#last.reverse is faster than Array#reverse.first and viceversa

### ISSUE THREAD

**Issue by Oppen** [DamirSvrtan/fasterer#56]
Running this code:
```ruby
#!/usr/bin/env ruby

require 'benchmark/ips'

ARR1 = [ 1, 2, 3 ] * 1_000_000

Benchmark.ips do |b|
  b.report('.reverse.first') do
    ARR1.reverse.first(1_000)
  end

  b.report('.last.reverse') do
    ARR1.last(1_000).reverse
  end

  b.compare!
end

Benchmark.ips do |b|
  b.report('.reverse.last') do
    ARR1.reverse.last(1_000)
  end

  b.report('.first.reverse') do
    ARR1.first(1_000).reverse
  end

  b.compare!
end
```
we see a huge speed difference for this simple synthetic benchmark:
```shell
Calculating -------------------------------------
      .reverse.first        24 i/100ms
       .last.reverse     80711 i/100ms
-------------------------------------------------
      .reverse.first      153.7 (±3.3%) i/s -        792 in   5.157104s
       .last.reverse  1155593.4 (±2.0%) i/s -    5811192 in   5.030946s

Comparison:
       .last.reverse:  1155593.4 i/s
      .reverse.first:      153.7 i/s - 7516.20x slower

Calculating -------------------------------------
       .reverse.last        25 i/100ms
      .first.reverse     83388 i/100ms
-------------------------------------------------
       .reverse.last      259.5 (±4.6%) i/s -       1300 in   5.022875s
      .first.reverse  1050525.6 (±8.4%) i/s -    5253444 in   5.047410s

Comparison:
      .first.reverse:  1050525.6 i/s
       .reverse.last:      259.5 i/s - 4048.21x slower
```
It's pretty intuitive that it works this way:
Let's say our array has N elements, and we want the last n but reversed.
We can either reverse it first, making N swaps (i.e. copies) and then copy the first n elements, making N+n copies, or we can take the last n elements, making n copies and then swap them n times, performing 2*n copies.

I'm working in a detector for these opportunities, but I don't know if I'll make it.

**Comment by Oppen** [comment]
Related PR to fast-ruby: https://github.com/JuanitoFatas/fast-ruby/pull/168

**Comment by Oppen** [comment]
I'm trying to find how to add the check, but I'm failing.
Is there any overview of how the detection works and how the code is organized?

**Comment by DamirSvrtan** [comment]
Hey @Oppen, thank you for a great find and your contribution! 🎉

There are a couple of ways Fasterer does detection:
- by looking at method calls
- by looking at method definitions
- by looking at rescue block presence

Each of them have a scanner inside of lib/scanner. The one that you are looking for is the method call.

A fairly similar checker for an offense would be the one where we look at `array.select {|x| x..}.first vs array.detect`. That one is on this line: https://github.com/DamirSvrtan/fasterer/blob/master/lib/fasterer/scanners/method_call_scanner.rb#L33

Let me know if you need more insight! cc @ringz3n for visibility.

**Comment by Oppen** [comment]
Ok, I think I get it. Thanks!
I'll try to have a PR around Monday.
Also, I thought of another one in the mean time, I'll create an issue
describing it later.

**Comment by Oppen** [comment]
Sorry for the delay. I just wanted to let you know that I'm still interested in submitting this improvement, but I'm currently preparing for finals and will lack the time for a few more weeks.
I'll mention the other idea I had just to make sure I don't forget it:
I've seen in my work's codebase that they tend to use ary.sort.first(10) to get the 10 greatest elements, which can be obtained by simply using ary.max(10), generally faster and in a more expressive way.
Similarly, ary.sort.reverse.first(10) or ary.sort.last(10).reverse can be replaced by ary.min(10).

**Comment by dukaev** [comment]
Hi @Oppen 👋
Notice [reek](https://github.com/troessner/reek).
It may be useful for your PR

**Comment by DamirSvrtan** [comment]
No worries @Oppen, take care of your finals first, no rush :)

I would leave the comment about using `max(10)` in the fast-ruby repo so they have it there reported, and then start reporting on it here.

**Comment by DamirSvrtan** [comment]
@Oppen any progress on getting this merged into fast ruby?

**Comment by Oppen** [comment]
I've been short of time. I'll try in the weekend.

**Comment by DamirSvrtan** [comment]
@Oppen any progress on getting this merged into fast ruby?

**Comment by DamirSvrtan** [comment]
@Oppen i'll be closing this as there hasn't been any work on it for a longer period of time, and the fast-ruby PR hasn't been merged in. If you want to continue working on this, feel free to open a new PR, and please make sure the change is in fast-ruby as well.

Best,
Damir
