### ISSUE TITLE
Useful references for rules

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [DamirSvrtan/fasterer#7]
https://www.omniref.com/github/JuanitoFatas/fast-ruby/HEAD

**Comment by DamirSvrtan** [comment]
Hey @JakeTheSnake3p0, what's the difference between viewing code on omniref and the fast-ruby repo?

Btw the link you sent returns 404's

**Comment by JakeTheSnake3p0** [comment]
Sorry, I was just browsing the web and came across the link; I figured there might have been some useful rules in there for this repo. I didn't look for the github repo as I didn't realize it would 404 so soon (or at all for that matter).
