### ISSUE TITLE
Run fasterer on specified files' list

### ISSUE THREAD

**Issue by Diego-Zulu** [DamirSvrtan/fasterer#75]
Hey there.

I was wondering if support for specifying a list of files to run Fasterer on could be added.

It would be really nice if we could make it work with xargs, I had this use case in mind: 

```echo app/controllers/application_controller.rb config/routes.rb | xargs bundle exec fasterer```

**Comment by DamirSvrtan** [comment]
Hi @Diego-Zulu!

I guess no one else encountered the need to do something like that so it was never implemented.

If you're willing to open a PR with the necessary changes I'd more than glad to review it!

**Comment by DamirSvrtan** [comment]
Hi @Diego-Zulu , any updates on this work?

Let me know whether you'd pick this work up or whether I should close this issue.

**Comment by DamirSvrtan** [comment]
Closing this issue as the issue author is not responding. I think it's a good improvement, I just don't have the time to do it though.
