### ISSUE TITLE
Required ruby version

### ISSUE THREAD

**Issue by biow0lf** [DamirSvrtan/fasterer#84]
Did `0.8.3` version really requires ruby `~> 2.2`? Can this requirements relaxed to `>= 2.2`?

**Comment by swiknaba** [comment]
when changing to `>= 2.2` (how about `>= 2.3` --it is soon 2021!) probably we also want to add Ruby 3.0 to the travis-yml (and drop 2.2.?).

2.3.0 was release on 2015-12-25.

**Comment by DamirSvrtan** [comment]
hi! 👋 We do not need to require only 2.x versions above 2.2, it was just added back when Ruby 3 was barely even mentioned :) We can relax the requirement to `>= 2.2`.

@swiknaba what would be the motivation to drop 2.2? I understand it is super old, but if it's not blocking our development in any way, i would rather keep it to provide support to folks that are stuck on 2.2. Let me know what you all think

**Comment by swiknaba** [comment]
My motivation to drop old versions from CI is to incur less CI runs for every push (thus saving money and time). Those few still running on super old versions could still run tests manually, and if failing, use an older version of the gem. --no strong opinion here though, I'm not paying for the CI of this project ;)

**Comment by DamirSvrtan** [comment]
> I'm not paying for the CI of this project ;)

Well, neither am I, it's an open source project.
