### ISSUE TITLE
Does not work if there are Ruby 3.0 one line methods in the code

### ISSUE THREAD

**Issue by volhit** [DamirSvrtan/fasterer#94]
Got ` Racc::ParseError - (string):3 :: parse error on value "=" (tEQL)`

Code example that break execution:
```ruby
module ToBoolean
  refine Object do
    def to_bool = ActiveRecord::Type::Boolean.new.cast(self)
  end

  refine TrueClass do
    def to_bool = self
  end

  refine FalseClass do
    def to_bool = self
  end

  refine NilClass do
    def to_bool = self
  end

  refine Numeric do
    def to_bool = !zero?
  end
end
```

**Comment by DamirSvrtan** [comment]
Hi! This is usually due to the ruby_parser not supporting that version of Ruby. It seems they however do support [Ruby 3.0](https://github.com/seattlerb/ruby_parser/blob/master/History.rdoc#label-3.18.0+-2F+2021-10-27), can you post which version of it are you using?

**Comment by DamirSvrtan** [comment]
There has been no follow up 3 months after my comment, closing out.
