### ISSUE TITLE
False positive for select_first_vs_detect when `first` is `first(N)`

### ISSUE THREAD

**Issue by owst** [DamirSvrtan/fasterer#99]
With this example code:
```ruby
(1..100).select { |i| i >= 50 }.first(5)
```
`fasterer 0.10.0` reports `Array#select.first is slower than Array#detect.`.

However, this is only true when `Enumerable#first` takes no argument; here we want the first 5 matching elements and detect does not support that functionality.

I suggest that this detector only fires when `first` is passed no argument

**Comment by DamirSvrtan** [comment]
hey @owst, thanks for reporting, I've released [fasterer 0.10.1](https://rubygems.org/gems/fasterer) with this bugfix!
